area_settings:
  start_point:
    - 0 #x
    - 0 #y
  paint_square_size: # size in meters
    - 4 #x
    - 4  #y

data_storage:
  trajectory_directory: "saves/trajectory"
  polynomials_directory: "saves/poly"