area_settings:
  start_point:
    - 0 #x
    - 0 #y
  paint_square_size: # size in meters
    - 6 #x
    - 6  #y

data_storage:
  trajectory_directory: "saves/trajectory"
  polynomials_directory: "saves/poly"